version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "ci: "

  - package-ecosystem: cargo
    directory: /src/rust
    schedule:
      interval: daily
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
    commit-message:
      prefix: "chore: "
    groups:
      patch:
        update-types:
          - patch
      strum:
        patterns:
          - "strum*"
    ignore:
      - dependency-name: tikv-jemallocator
        versions:
          - "0.6.1"

  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "build(devcontainer): "
