[package]
name = 'r-polars'     # r-polars
version = '0.1.0'     # this version no is not used
edition = '2021'
rust-version = "1.65"

[lib]
crate-type = ['staticlib']

[features]
default = []
simd = ["polars/simd"]

[workspace]
# prevents package from thinking it's in the workspace
[target.'cfg(any(not(target_os = "linux"), use_mimalloc))'.dependencies]
mimalloc = { version = "0.1.34", default-features = false }

[target.'cfg(all(target_os = "linux", not(use_mimalloc)))'.dependencies]
jemallocator = { version = "0.5.0", features = ["disable_initial_exec_tls"] }


# use opt-level = 1 for argminmax package unless profile is profile.release-optimized for to support Rust < 1.66
[profile.release-optimized]
inherits = "release"
[profile.release.package.argminmax]
opt-level = 1
[profile.release-optimized.package.argminmax]
opt-level = 3

[dependencies]
extendr-api = { git = "https://github.com/rpolars/extendr", branch = "pl0.7.0rc", default-features = false, features = [
  "result_list",
] }

flume = "0.10.14"
state = "0.5.3"
rayon = "1.6.1"
smartstring = "1.0.1"
serde_json = "*"
thiserror = "1.0.40"
indenter = "0.3.3"
polars-core = { git = "https://github.com/pola-rs/polars.git", rev = "ee2366b68f35c4b69dfe34cbf1eae107d4ebe97b", default_features = false }


#features copied from node-polars
[dependencies.polars]
features = [
  "rolling_window",
  "json",
  "dynamic_groupby",
  "zip_with",
  "lazy",
  "strings",
  "temporal",
  "random",
  "object",
  "csv",
  "fmt",
  "performant",
  "dtype-full",
  "rows",
  "private",
  "round_series",
  "is_in",
  "is_first",
  "asof_join",
  "cross_join",
  "dot_product",
  "concat_str",
  "row_hash",
  "reinterpret",
  "decompress-fast",
  "mode",
  "extract_jsonpath",
  "lazy_regex",
  "cum_agg",
  "rolling_window",
  "repeat_by",
  "interpolate",
  #"list",
  "ewma",
  "rank",
  "diff",
  "pct_change",
  "moment",
  "arange",
  "true_div",
  "dtype-categorical",
  "diagonal_concat",
  "horizontal_concat",
  "abs",
  "dot_diagram",
  "dataframe_arithmetic",
  "json",
  "string_encoding",
  "product",
  "ndarray",
  "unique_counts",
  "log",
  "serde-lazy",
  "partition_by",
  "pivot",
  "semi_anti_join",
  "parquet",
  "to_dummies",
  "ipc",
  "avro",
  "list_eval",
  "arg_where",
  #extra features since copy from node-polars
  "top_k",
  "search_sorted",
  "propagate_nans",
  "trigonometry",
  "sign",
  "cumulative_eval",
  "list_eval",
  "list_to_struct",
  "list_take",
  "timezones",
  "date_offset",
  "dtype-date",
  "dtype-datetime",
  "dtype-time",
  "dtype-duration",
  "date_offset",
  "string_justify",
  "is_unique",
  "binary_encoding",
  "string_from_radix",
  "meta",
  "approx_unique",
]
default-features = false
git = "https://github.com/pola-rs/polars.git"
rev = "ee2366b68f35c4b69dfe34cbf1eae107d4ebe97b"
