[package]
name = "r-polars"
version = "0.35.1"
edition = "2021"
rust-version = "1.73"
publish = false

[lib]
crate-type = ['staticlib']

[features]
default = []
full_features = ["simd", "sql"]
simd = ["polars/simd"]
sql = ["polars/sql"]
rpolars_debug_print = []

[workspace]
# prevents package from thinking it's in the workspace
[target.'cfg(any(not(target_os = "linux"), use_mimalloc))'.dependencies]
mimalloc = { version = "0.1.34", default-features = false }

[target.'cfg(all(target_os = "linux", not(use_mimalloc)))'.dependencies]
jemallocator = { version = "0.5.0", features = ["disable_initial_exec_tls"] }

[profile.release-optimized]
inherits = "release"
codegen-units = 1
lto = "fat"
strip = true

[profile.release.package.argminmax]
opt-level = 3 # was 1 to support 1.66, but since 1.70 is needed anyway it does not matter anymore
[profile.release-optimized.package.argminmax]
opt-level = 3

[dependencies]
extendr-api = { git = "https://github.com/extendr/extendr", rev = "0ac58377c50174818e02de54b1032c5f4cb75e4f", default-features = false, features = [
  "result_list",
  "serde",
] }
flume = "0.11.0"
indenter = "0.3.3"
ipc-channel = "0.18.0"
once_cell = "1.19.0"
rayon = "1.6.1"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "*"
smartstring = "1.0.1"
state = "0.6.0"
thiserror = "1.0.40"
polars-core = { git = "https://github.com/pola-rs/polars.git", rev = "f96d2cd5b70ee8d7412971d0d057f3f523a91bb1", default-features = false }
polars-lazy = { git = "https://github.com/pola-rs/polars.git", rev = "f96d2cd5b70ee8d7412971d0d057f3f523a91bb1", default-features = false }
either = "1"
#features copied from node-polars

[dependencies.polars]
features = [
  "abs",
  "approx_unique",
  "arg_where",
  "asof_join",
  "avro",
  "binary_encoding",
  "concat_str",
  "cov",
  "cross_join",
  "cse",
  "cum_agg",
  "cumulative_eval",
  "dataframe_arithmetic",
  "date_offset",
  "decompress-fast",
  "diagonal_concat",
  "diff",
  "dot_diagram",
  "dot_product",
  "dtype-categorical",
  "dtype-date",
  "dtype-datetime",
  "dtype-duration",
  "dtype-full",
  #"dtype-struct",
  "dtype-time",
  "dynamic_group_by",
  "extract_jsonpath",
  "ewma",
  "fmt",
  "horizontal_concat",
  "interpolate",
  "ipc",
  "is_first_distinct",
  "is_last_distinct",
  "is_in",
  "is_unique",
  "json",
  "lazy",
  "lazy_regex",
  #"list",
  "list_eval",
  "list_gather",
  "list_to_struct",
  "log",
  "meta",
  "mode",
  "moment",
  "ndarray",
  "object",
  "parquet",
  "partition_by",
  "pct_change",
  "peaks",
  "performant",
  "pivot",
  "product",
  "propagate_nans",
  "random",
  "range",
  "rank",
  "reinterpret",
  "repeat_by",
  "rolling_window",
  "round_series",
  "row_hash",
  "rows",
  "semi_anti_join",
  "search_sorted",
  "serde-lazy",
  "sign",
  "strings",
  "string_encoding",
  "string_pad",
  "string_to_integer",
  "temporal",
  "timezones",
  "to_dummies",
  "top_k",
  "trigonometry",
  "true_div",
  "unique_counts",
  "zip_with",
]
git = "https://github.com/pola-rs/polars.git"
rev = "f96d2cd5b70ee8d7412971d0d057f3f523a91bb1"
