[package]
name = "r-polars"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["staticlib", "lib"]

[profile.release]
panic = "unwind"

[dependencies]
ciborium = "0.2"
flume = "0.11"
polars-core = { git = "https://github.com/pola-rs/polars.git", rev = "962b576b1cc678840d52fdcd67a1c117db49d0bb", default-features = false }
polars-error = { git = "https://github.com/pola-rs/polars.git", rev = "962b576b1cc678840d52fdcd67a1c117db49d0bb", default-features = false }
savvy = "0.6.7"
serde_json = "1"
state = "0.6"
strum = "0.26"
strum_macros = "0.26"
thiserror = "1"

[dependencies.polars]
git = "https://github.com/pola-rs/polars.git"
rev = "962b576b1cc678840d52fdcd67a1c117db49d0bb"
features = [
    "binary_encoding",
    "cse",
    "diff",
    "dtype-full",
    "fused",
    "json",
    "lazy",
    "meta",
    "parquet",
    "propagate_nans",
    "serde",
    "serde-lazy",
    "streaming",
    "temporal",
    "timezones",
]

[target.'cfg(all(any(not(target_family = "unix"), allocator = "mimalloc")))'.dependencies]
mimalloc = { version = "0.1", default-features = false }

[target.'cfg(all(target_family = "unix", not(target_os = "macos"), not(allocator = "mimalloc")))'.dependencies]
jemallocator = { version = "0.5", features = [
    "disable_initial_exec_tls",
    "background_threads",
] }

[target.'cfg(all(target_family = "unix", target_os = "macos", not(allocator = "mimalloc")))'.dependencies]
jemallocator = { version = "0.5", features = ["disable_initial_exec_tls"] }
