[package]
name = "r-polars"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["staticlib", "lib"]

[profile.release]
panic = "unwind"

[dependencies]
ciborium = "0.2"
flume = "0.11"
polars-core = { git = "https://github.com/pola-rs/polars.git", rev = "f0d087dd213a0baab2c721a21addf009382b3cc1", default-features = false }
polars-error = { git = "https://github.com/pola-rs/polars.git", rev = "f0d087dd213a0baab2c721a21addf009382b3cc1", default-features = false }
savvy = "0.7"
serde_json = "1"
state = "0.6"
strum = "0.26"
strum_macros = "0.26"
thiserror = "1"

[dependencies.polars]
git = "https://github.com/pola-rs/polars.git"
rev = "f0d087dd213a0baab2c721a21addf009382b3cc1"
features = [
    "array_any_all",
    "array_count",
    "array_to_struct",
    "binary_encoding",
    "business",
    "cloud",
    "concat_str",
    "cse",
    "csv",
    "diagonal_concat",
    "diff",
    "dtype-full",
    "extract_groups",
    "extract_jsonpath",
    "find_many",
    "fused",
    "ipc",
    "ipc_streaming",
    "is_in",
    "json",
    "lazy",
    "list_any_all",
    "list_count",
    "list_drop_nulls",
    "list_eval",
    "list_gather",
    "list_sample",
    "list_sets",
    "list_to_struct",
    "meta",
    "month_start",
    "month_end",
    "offset_by",
    "parquet",
    "propagate_nans",
    "range",
    "serde",
    "serde-lazy",
    "streaming",
    "strings",
    "string_encoding",
    "string_pad",
    "string_reverse",
    "string_to_integer",
    "temporal",
    "timezones",
]

[target.'cfg(all(any(not(target_family = "unix"), allocator = "mimalloc")))'.dependencies]
mimalloc = { version = "0.1", default-features = false }

[target.'cfg(all(target_family = "unix", not(target_os = "macos"), not(allocator = "mimalloc")))'.dependencies]
jemallocator = { version = "0.5", features = [
    "disable_initial_exec_tls",
    "background_threads",
] }

[target.'cfg(all(target_family = "unix", target_os = "macos", not(allocator = "mimalloc")))'.dependencies]
jemallocator = { version = "0.5", features = ["disable_initial_exec_tls"] }
